---
- name: Install NGINX
  hosts: lighthouse
  tags: lighthouse
  become: true
  handlers:
    - name: Start-nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
      listen: start-nginx
    - name: Reload-nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: reload-nginx

  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: start-nginx

    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: reload-nginx
  tags: nginx      

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Reload-nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      listen: reload-nginx
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present

  tasks:
    - name: Lighthouse | Get from source
      ansible.builtin.git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location }}"

    - name: Lighthouse | Create Lighthouse config
      become: true
      ansible.builtin.template:
        src: templates/lighthouse.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: reload-nginx
  tags: lighthouse

- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse block
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: '0644'
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        disable_gpg_check: true
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
  tags: clickhouse

- name: Install Vector
  hosts: vector
  handlers:
    - name: Restart vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
        enabled: true
  tasks:

    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
        dest: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
        mode: '0644'

    - name: Install vector
      become: true
      ansible.builtin.yum:
        disable_gpg_check: true
        name:
          - /tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm

    - name: Copy vector config
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
        mode: '0644'
        owner: root
        group: root

      notify:
        - Restart vector
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
  tags: vector
